---
title: 3MUGIS
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: yaroslavtsevam@gmail.com
url: http://3mugis.org
description: The 3MUGIS school organized by RUDN University (Moscow, Russia) in collaboration
  with Urban Soil Institute (New York, USA) and under umbrella of the International
  Union of Soil Science (IUSS).
intro: May 21 â€“ 30, 2018 RUDN University, Moscow, Russia
meta_author: Alex Yaroslavtsev
google_verify: 
bing_verify: 
contact: static
disqus_shortname: myshortname
color:
  primary: 18bc9c
  primary-rgb: '24,288,156'
  secondary: 2c3e50
  secondary-dark: 233140
footer:
  copyright: RUDN University
  location: Location
  social: Also look at
  credits: Credits
social:
- title: twitter
  url: http://twitter.com/jekyllrb
- title: facebook
  url: http://www.facebook.com/groups/1191891174204804/
- title: stack-overflow
  url: http://stackoverflow.com/questions/tagged/jekyll
- title: bitbucket
  url: http://bitbucket.org/jekyll
- title: github
  url: http://github.com/jekyll
address:
- line: 117198, Moscow, Miklukho-Maklaya str. 6
- line: 'Tel.: +7 (495) 434 5300'
credits: The 3MUGIS school is organized by RUDN University (Moscow, Russia) in collaboration
  with Urban Soil Institute (New York, USA) and under umbrella of the International
  Union of Soil Science (IUSS),   Moscow, May 2017
markdown: kramdown
permalink: pretty
